package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.application.Application;
import javafx.event.ActionEvent;

public class POSUnitController extends Application{
	 Stage st = new Stage();
	@FXML
	private TextField txfUnit;
	@FXML
	public  Button btnSave;
	@FXML
	private Button btnCancel;
	@FXML
	private Button btnClose;
	double x,y;
	int unit;
    public int getUnit() {
		return unit;
	}

	public void setUnit(int unit) {
		this.unit = unit;
	}

	@FXML
    void dragged(MouseEvent event) {
    	Stage stage=(Stage)((Node) event.getSource()).getScene().getWindow();
    	stage.setX(event.getSceneX()-x);
    	stage.setY(event.getSceneY()-y);
    }

    @FXML
    void pressed(MouseEvent event) {
    	x=event.getSceneX();
    	y=event.getSceneY();
    }
    @FXML
    void btnCloseOnAction(ActionEvent event) {
    	Stage stage=(Stage)((Node) event.getSource()).getScene().getWindow();
    	stage.close();
    }

	// Event Listener on TextField[#txfUnit].onAction
	@FXML
	public void txfUnitOnAction(ActionEvent event) {
		// TODO Autogenerated
	} 
	// Event Listener on Button[#btnSave].onAction
	@FXML
	public void btnSaveOnAction(ActionEvent event) {
		if (!txfUnit.getText().isEmpty()&&txfUnit.getText().matches("\\d*")) {
				
			if (Integer.parseInt(txfUnit.getText())<=POSDBcontrol.getResidualItem(PosController.selected.getItem_ID())) {
				PosController.setUnitData(Integer.parseInt(txfUnit.getText()));
				Stage stage=(Stage)((Node) event.getSource()).getScene().getWindow();
		    	stage.close();
			}else {
				new Alert(AlertType.INFORMATION,"Not enough item.\nWe only have "+PosController.selected.getQuantity()+ ""+ POSDBcontrol.getUnit(Integer.parseInt(PosController.selected.getUnit_Name()))+" Left",ButtonType.CLOSE).show();
				txfUnit.clear();
			}
		}else {
			new Alert(AlertType.INFORMATION,"Please Input A Valid Number ",ButtonType.CLOSE).show();

		}
	}
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void btnCancelOnAction(ActionEvent event) {
		Stage stage=(Stage)((Node) event.getSource()).getScene().getWindow();
    	stage.close();
	}
 
	@Override
	public void start(Stage primaryStage) throws Exception {
		try {
			BorderPane root = (BorderPane)FXMLLoader.load(getClass().getResource("POSUnit.fxml"));
			Scene scene = new Scene(root,400,200);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.initStyle(StageStyle.TRANSPARENT);
			primaryStage.setScene(scene);
			primaryStage.show();
			st = primaryStage;
		} catch(Exception e) {
			e.printStackTrace();
		}
		
	}
	public  Stage getSt() {
		return st;
	}

	public  void setSt(Stage stg) {
		st = stg;
	}

	

}
