package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

public class SampleController {
	@FXML
	private Button save;
	@FXML
	private Button cancel;
	@FXML
	private TextField txfUnitCategoryName;
	@FXML
	private TextArea txaUnitCategoryRemark;

	// Event Listener on Button[#save].onAction
	@FXML
	public void saveOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancel].onAction
	@FXML
	public void cancelOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#txfUnitCategoryName].onAction
	@FXML
	public void txfUnitCategoryNameOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
